image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      echo "Gitpod init. Setting up ambianic-edge dev environment."
      pip3 install -e ./src
    command: echo "Starting ambianic-edge in gitpod"
